version: '3.8'

services:
    backend:
        container_name: nestjs-vehiculos
        build: .
        depends_on:
            - database
        networks:
            - backend

    database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: example
        # volumes:
        #     - ~/backend-vehiculos-data:/var/lib/mysql
        networks:
            - backend

networks:
    backend:
        driver: 'bridge'
